apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sampleappv1 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sampleappv1 
    spec:
      containers:
        - name: sampleappv1 
          image: reviewapp.azurecr.io/sampleappv1
          ports:
          - containerPort: 80